### ISSUE TITLE
radiomics.uk - Bad gateway Error code 502

### ISSUE THREAD

**Issue by SimonLBSoerensen** [pwoznicki/radiomics-features#2]
Dear pwoznicki,

Great work with RadiomicsHub!

Your website seems to be down: Bad gateway Error code 502

![image](https://github.com/user-attachments/assets/a8562ba4-fc8d-4cdd-b607-ced7aa75dc7e)

Best
Simon

**Comment by pwoznicki** [comment]
Thank you Simon and sorry for the invonvenience. You should now be able to reach it again (https://radiomics.uk/).

Best regards, Piotr

**Comment by SimonLBSoerensen** [comment]
Thank Piotr! 
Great showcase website

Best 
Simon

**Comment by popleyi** [comment]
It seems that https://radiomics.uk/ is down. Bad gateway Error code 502. Thanks for the nice work.

**Comment by pwoznicki** [comment]
hey @popleyi, thanks for noticing that. It should be back up!
